[path]
session_path = "data/session"
session_history_path = "data/session/history"
workspace_base_path = "data/workspace_base"
sandbox_home_path = "data/sandbox-home"

[llm]
api_base = "http://llm-proxy.1393074507312057.cn-wulanchabu.pai-eas.aliyuncs.com/v1"
default_model = "openai/Kimi-K2.6"
default_context_token = 256000
default_top_p = 0.7
tools_python_package = "custom_tools"
default_tools = ["echo", "hello"]
system_name = ""
custom_system_prompt = ""
# default_reasoning_effort = "normal"
support_image = true
support_video = true
support_json_output = true
parallel = 4
max_iterations = 40

[tool]
cdp_url = "ws://browserless:3000"

[tool.browser_preview]
browser_preview_base_url = "http://backend:7878/browser_preview"
browser_preview_path = "data/browser_preview"

# [tool.mcpServers.filesystem]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-filesystem", "."]
# enabled_tools = ["*"]
# tool_timeout = 30

# [tool.mcpServers.my-api]
# url = "https://mcp.example.com/sse"
# headers = { Authorization = "Bearer xxx" }
# enabled_tools = ["*"]
# tool_timeout = 120


[feishu]
app_id = "cli_aa8fcbaccae41cba"
idle_timeout = 5
cache_path = "data/feishu_cache"
