[path]
session_path = "session"
session_history_path = "session/history"
workspace_base_path = "workspace_base"

[llm]
api_base = "http://10.4.71.158:4000/v1"
default_model = "openai/Kimi-K2.6"
default_context_token = 256000
default_top_p = 0.7
tools_python_package = "custom_tools"
default_tools = ["echo", "hello"]
system_name = ""
custom_system_prompt = ""
# default_reasoning_effort = "normal"
support_image = true
support_video = true
support_json_output = true

[feishu]
app_id = "cli_a99b80eb143c9013"
idle_timeout = 5
parallel = 3
